export const CREATE_RECEPTION  = 'CREATE_RECEPTION';
export const REMOVE_RECEPTION  = 'REMOVE_RECEPTION';
export const CHANGE_RECEPTION  = 'CHANGE_RECEPTION';
export const UPLOAD_RECEPTIONS = 'UPLOAD_RECEPTIONS';